services:
  backend:
    build:
      context: ./urlgoatbackend
      dockerfile: Dockerfile
    ports:
      - "5150:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      MSSQL_AGENT_ENABLED: false  # Disable SQL Server Agent
      MSSQL_LOG_QUERIES: "ON"    # Set to "ON" to log queries
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr & 
        sleep 60
        /opt/mssql-tools/bin/sqlcmd -S sql_server2022 -U SA -P S3cur3P@ssW0rd! -d master -i /docker-entrypoint-initdb.d/setup.sql
        tail -f /dev/null #Keeps the container running   
  angular:
    build:
      context: ./urlgoatfrontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend