version: '3'
services:
  app:
    build:
      context: ./Docker/aspnetcore
      dockerfile: Dockerfile
    ports:
      - "7203:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=urlshortenertest;User=sa;Password=YourStrongPassword;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"

  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: YourStrongPassword
      ACCEPT_EULA: Y
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d  # Mount the sql-scripts directory into the SQL Server container

  frontend:
    build:
      context: ./Docker/Angular
      dockerfile: Dockerfile
    ports:
      - "4200:80"